config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root "home#index"
    resources :atendimentos
    resources :estoques
    resources :servicos
    resources :funcionarios
    resources :clientes
    resources :veiculos
    resources :pecas
    resources :venda_servicos
    resources :agendamentos do
      patch :update_status, on: :collection
    end
    resources :clientes do
      get :veiculos, on: :member
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/agendamento.rb
class Agendamento < ApplicationRecord
  belongs_to :veiculo
  belongs_to :servico

  enum :status, { pendente: 0, confirmado: 1, reprovado: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :veiculo
  has_and_belongs_to_many :funcionarios

  enum :status, { agendado: 0, andamento: 1, concluido: 2, cancelado: 3 }

  validates :data_inicio, :data_termino, :status, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_one :user, dependent: :destroy
  has_many :veiculos, dependent: :destroy

  validates :nome, presence: true, length: { in: 3..80 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :telefone, presence: true, length: { minimum: 11, maximum: 11 }
  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11, maximum: 11 }
  validates :endereco, presence: true, length: { in: 3..80 }
end

app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :peca

  validates :codigo, presence: true, uniqueness: true
  validates :quantidade, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  has_and_belongs_to_many :atendimentos

  validates :matricula, presence: true, uniqueness: true
  validates :nome, presence: true, length: { in: 3..80 }
  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11, maximum: 11 }
  validates :cargo, presence: true, length: { minimum: 5 }
  validates :email, presence: true
  validates :salario, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :data_admissao, presence: true
end

app/models/peca.rb
class Peca < ApplicationRecord
  has_many :estoques, dependent: :destroy

  validates :codigo, presence: true, uniqueness: true
  validates :nome, presence: true, length: { in: 2..20 }
  validates :preco, :tipo, :fabricante, :data_validade, presence: true
end

app/models/servico.rb
class Servico < ApplicationRecord
  has_many :atendimentos

  validates :codigo, presence: true, uniqueness: true
  validates :nome, presence: true
  validates :descricao, presence: true, length: { maximum: 100 }
  validates :preco, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :cliente, optional: true

  enum :role, [ :cliente, :admin ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente
  has_many :atendimentos

  validates :placa, presence: true, uniqueness: true, length: { minimum: 7, maximum: 7 }
  validates :modelo, presence: true, length: { minimum: 3, maximum: 30 }
  validates :ano, presence: true, numericality: { only_integer: true }
  validates :cor, presence: true, length: { minimum: 3, maximum: 15 }
  validates :quilometragem, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :chassi, presence: true, length: { minimum: 17, maximum: 17 }, uniqueness: { case_sensitive: false }

end

app/models/venda_servico.rb
class VendaServico < ApplicationRecord
  belongs_to :servico
  belongs_to :cliente
  belongs_to :veiculo
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      render :index_admin
    else
      render :index_cliente
    end
  end
end

app/controllers/pecas_controller.rb
class PecasController < AdminController
  before_action :set_peca, only: %i[ show edit update destroy ]

  # GET /pecas or /pecas.json
  def index
    @pecas = Peca.all
  end

  # GET /pecas/1 or /pecas/1.json
  def show
  end

  # GET /pecas/new
  def new
    @peca = Peca.new
  end

  # GET /pecas/1/edit
  def edit
  end

  # POST /pecas or /pecas.json
  def create
    @peca = Peca.new(peca_params)
    handle_save(@peca.save, :new, "Peça cadastrada com sucesso.")
  end

  # PATCH/PUT /pecas/1 or /pecas/1.json
  def update
    handle_save(@peca.update(peca_params), :edit, "Peça atualizada com sucesso.")
  end

  # DELETE /pecas/1 or /pecas/1.json
  def destroy
    @peca.destroy!

    respond_to do |format|
      format.html { redirect_to pecas_url, notice: "Peça excluída com sucesso." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_peca
    @peca = Peca.find_by(id: params[:id])
    if @peca.nil?
      redirect_to pecas_path, notice: "Peça não encontrada."
    end
  end

  # Only allow a list of trusted parameters through.
  def peca_params
    params.require(:peca).permit(:codigo, :nome, :preco, :tipo, :fabricante, :data_validade)
  end

  def handle_save(method_success, render_template, notice_message)
    respond_to do |format|
      if method_success
        format.html { redirect_to peca_url(@peca), notice: notice_message }
        format.json { render :show, status: :ok, location: @peca }
      else
        format.html { render render_template, status: :unprocessable_entity }
        format.json { render json: @peca.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_class(status)
    case status
    when "pendente", "agendado"
      "badge-pending"
    when "confirmado"
      "badge-confirmed"
    when "andamento"
      "badge-in-progress"
    when "concluido"
      "badge-completed"
    else
      "badge-secondary"
    end
  end

  def confirm_delete_button(name, path, options = {})
    default_options = { method: :delete, data: { turbo_confirm: "Tem certeza que deseja excluir?" } }
    options = default_options.merge(options)
    button_to name, path, options
  end
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/pecas/_form.html.erb
<%= form_with(model: peca, local: true) do |form| %>
  <% if peca.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(peca.errors.count, "erro") %> <%= "encontrado".pluralize(peca.errors.count) %>:</h4>
      <ul>
        <% peca.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :codigo, "Código", class: "form-label" %>
    <%= form.text_field :codigo, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :nome, "Nome", class: "form-label" %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :preco, "Preço", class: "form-label" %>
    <%= form.text_field :preco, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :tipo, "Tipo", class: "form-label" %>
    <%= form.text_field :tipo, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :fabricante, "Fabricante", class: "form-label" %>
    <%= form.text_field :fabricante, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :data_validade, "Data de Validade", class: "form-label" %>
    <%= form.date_field :data_validade, class: "form-control" %>
  </div>

  <div class="text-center">
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pecas/_peca.html.erb
<div id="<%= dom_id peca %>">
  <p>
    <strong>Código:</strong>
    <%= peca.codigo %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= peca.nome %>
  </p>

  <p>
    <strong>Preço:</strong>
    <%= peca.preco %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= peca.tipo %>
  </p>

  <p>
    <strong>Fabricante:</strong>
    <%= peca.fabricante %>
  </p>

  <p>
    <strong>Data de validade:</strong>
    <%= peca.data_validade %>
  </p>

</div>

app/views/pecas/edit.html.erb
<% content_for :title, "Editar peça" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="d-flex align-items-center mb-4">
        <%= link_to "Voltar ", pecas_path, class: "btn btn-secondary me-3" %>
        <div class="flex-grow-1 text-center">
          <h1>Editar peça</h1>
        </div>
        <div class="fixed-size-div"></div>
      </div>

      <%= render "form", peca: @peca %>
    </div>
  </div>
</div>

app/views/pecas/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Peças" %>


<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>Peças</h1>
  <%= link_to "Nova peça", new_peca_path, class: "btn btn-primary" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Preço</th>
      <th>Tipo</th>
      <th>Fabricante</th>
      <th>Data de Validade</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @pecas.each do |peca| %>
      <tr>
        <td><%= peca.codigo %></td>
        <td><%= peca.nome %></td>
        <td><%= number_to_currency(peca.preco, unit: "R$") %></td>
        <td><%= peca.tipo %></td>
        <td><%= peca.fabricante %></td>
        <td><%= peca.data_validade.strftime("%d/%m/%Y") %></td>
        <td><%= link_to "Exibir", peca, class: "btn btn-info btn-sm" %></td>
        <td><%= link_to "Editar", edit_peca_path(peca), class: "btn btn-warning btn-sm" %></td>
        <td>
          <%= confirm_delete_button "Excluir", peca, { class: "btn btn-danger btn-sm" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pecas/new.html.erb
<% content_for :title, "Novo peça" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="d-flex align-items-center mb-4">
        <%= link_to "Voltar ", pecas_path, class: "btn btn-secondary me-3" %>
        <div class="flex-grow-1 text-center">
          <h1>Novo peça</h1>
        </div>
        <div class="fixed-size-div"></div>
      </div>

      <%= render "form", peca: @peca %>
    </div>
  </div>
</div>

app/views/pecas/show.html.erb
<%= content_for :title, "Detalhes do peça" %>

<div class="container mt-4">
  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>

  <div class="mb-4">
    <%= render @peca %>
  </div>

  <div class="d-flex justify-content-between">
    <div>
      <%= link_to "Voltar para peças", pecas_path, class: "btn btn-secondary" %>
    </div>
    <div class="d-flex">
      <%= link_to "Editar peça", edit_peca_path(@peca), class: "btn btn-warning me-2" %>
      <%= confirm_delete_button "Excluir peça", @peca, { class: "btn btn-danger" } %>
    </div>
  </div>
</div>