config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root "home#index"
    resources :atendimentos
    resources :estoques
    resources :servicos
    resources :funcionarios
    resources :clientes
    resources :veiculos
    resources :pecas
    resources :venda_servicos
    resources :agendamentos do
      patch :update_status, on: :collection
    end
    resources :clientes do
      get :veiculos, on: :member
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/agendamento.rb
class Agendamento < ApplicationRecord
  belongs_to :veiculo
  belongs_to :servico

  enum :status, { pendente: 0, confirmado: 1, reprovado: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :veiculo
  has_and_belongs_to_many :funcionarios

  enum :status, { agendado: 0, andamento: 1, concluido: 2, cancelado: 3 }

  validates :data_inicio, :data_termino, :status, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_one :user, dependent: :destroy
  has_many :veiculos, dependent: :destroy

  validates :nome, presence: true, length: { in: 3..80 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :telefone, presence: true, length: { minimum: 11, maximum: 11 }
  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11, maximum: 11 }
  validates :endereco, presence: true, length: { in: 3..80 }
end

app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :peca

  validates :codigo, presence: true, uniqueness: true
  validates :quantidade, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  has_and_belongs_to_many :atendimentos

  validates :matricula, presence: true, uniqueness: true
  validates :nome, presence: true, length: { in: 3..80 }
  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11, maximum: 11 }
  validates :cargo, presence: true, length: { minimum: 5 }
  validates :email, presence: true
  validates :salario, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :data_admissao, presence: true
end

app/models/peca.rb
class Peca < ApplicationRecord
  has_many :estoques, dependent: :destroy

  validates :codigo, presence: true, uniqueness: true
  validates :nome, presence: true, length: { in: 2..20 }
  validates :preco, :tipo, :fabricante, :data_validade, presence: true
end

app/models/servico.rb
class Servico < ApplicationRecord
  has_many :atendimentos

  validates :codigo, presence: true, uniqueness: true
  validates :nome, presence: true
  validates :descricao, presence: true, length: { maximum: 100 }
  validates :preco, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :cliente, optional: true

  enum :role, [ :cliente, :admin ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente
  has_many :atendimentos

  validates :placa, presence: true, uniqueness: true, length: { minimum: 7, maximum: 7 }
  validates :modelo, presence: true, length: { minimum: 3, maximum: 30 }
  validates :ano, presence: true, numericality: { only_integer: true }
  validates :cor, presence: true, length: { minimum: 3, maximum: 15 }
  validates :quilometragem, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :chassi, presence: true, length: { minimum: 17, maximum: 17 }, uniqueness: { case_sensitive: false }

end

app/models/venda_servico.rb
class VendaServico < ApplicationRecord
  belongs_to :servico
  belongs_to :cliente
  belongs_to :veiculo
end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :set_agendamento, only: %i[show edit update destroy]
  before_action :set_veiculos, only: %i[new edit create update]

  # GET /agendamentos or /agendamentos.json
  def index
    @funcionarios = Funcionario.all
    if current_user.admin?
      @agendamentos = Agendamento.all
    else
      @agendamentos = Agendamento.joins(:veiculo)
                                 .where(veiculos: { cliente_id: current_user.cliente_id })
    end
  end

  # GET /agendamentos/1 or /agendamentos/1.json
  def show
  end

  # GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
  end

  # GET /agendamentos/1/edit
  def edit
  end

  # POST /agendamentos or /agendamentos.json
  def create
    @agendamento = Agendamento.new(agendamento_params)
    handle_save(@agendamento.save, :new, "Agendamento criado com sucesso.")
  end

  # PATCH/PUT /agendamentos/1 or /agendamentos/1.json
  def update
    handle_save(@agendamento.update(agendamento_params), :edit, "Agendamento atualizado com sucesso.")
  end

  # DELETE /agendamentos/1 or /agendamentos/1.json
  def destroy
    @agendamento.destroy

    respond_to do |format|
      format.html { redirect_to agendamentos_url, notice: "Agendamento excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  def update_status
    @agendamento = Agendamento.find_by(id: params[:agendamento_id])
    new_status = params[:status]
    funcionarios_ids = params[:funcionario_ids].reject!(&:blank?)

    if funcionarios_ids.empty?
      redirect_to agendamentos_path, alert: "É necessário selecionar pelo menos um funcionário para atualizar o status."
      return
    end

    if @agendamento.update(status: new_status)
      notice_message = handle_status_change(new_status)
      redirect_to agendamentos_path, notice: notice_message
    else
      redirect_to agendamentos_url, alert: "Não foi possível atualizar o status do agendamento."
    end
  end

  private

  def handle_save(method_success, render_template, notice_message)
    respond_to do |format|
      if method_success
        format.html { redirect_to agendamento_url(@agendamento), notice: notice_message }
        format.json { render :show, status: :created, location: @agendamento }
      else
        format.html { render render_template, status: :unprocessable_entity }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_agendamento
    @agendamento = Agendamento.find_by(id: params[:id])
    if @agendamento.nil?
      redirect_to atendimentos_path, notice: "Agendamento não encontrado."
    end
  end

  def set_veiculos
    if current_user.admin?
      @veiculos = Veiculo.all
    else
      @veiculos = current_user.cliente.veiculos
    end
  end

  def agendamento_params
    params.require(:agendamento).permit(:veiculo_id, :servico_id, :status, :data)
  end

  def handle_status_change(status)
    if status == "confirmado"
      create_atendimento
      "Agendamento aprovado. O atendimento logo será agendado."
    else
      "Agendamento reprovado."
    end
  end

  def create_atendimento
    atendimento = Atendimento.create!(
      veiculo: @agendamento.veiculo,
      data_inicio: @agendamento.data,
      data_termino: @agendamento.data,
      status: :agendado
    )
    funcionarios = Funcionario.where(id: params[:funcionario_ids])
    atendimento.funcionarios << funcionarios
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      render :index_admin
    else
      render :index_cliente
    end
  end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_class(status)
    case status
    when "pendente", "agendado"
      "badge-pending"
    when "confirmado"
      "badge-confirmed"
    when "andamento"
      "badge-in-progress"
    when "concluido"
      "badge-completed"
    else
      "badge-secondary"
    end
  end

  def confirm_delete_button(name, path, options = {})
    default_options = { method: :delete, data: { turbo_confirm: "Tem certeza que deseja excluir?" } }
    options = default_options.merge(options)
    button_to name, path, options
  end
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/agendamentos/_agendamento.html.erb
<div id="<%= dom_id agendamento %>">
  <p>
    <strong>Veiculo:</strong>
    <%= agendamento.veiculo_id %>
  </p>

  <p>
    <strong>Servico:</strong>
    <%= agendamento.servico_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= agendamento.status %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= agendamento.data %>
  </p>

</div>

app/views/agendamentos/_approve_status_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="approveStatusModal" tabindex="-1" aria-labelledby="approveStatusModal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="approveStatusModalLabel">Aprovar Status do Agendamento</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: update_status_agendamentos_path, method: :patch, remote: true, id: "updateStatusForm" do |form| %>
          <%= hidden_field_tag :agendamento_id, nil, id: "modal_agendamento_id" %>
          <%= form.hidden_field :status, id: "modal_status_field" %>
          <%= form.label :funcionario_ids, "Funcionário(s)", class: "form-label" %>
          <% if @funcionarios.any? %>
            <%= form.collection_check_boxes :funcionario_ids, @funcionarios, :id, :nome do |b| %>
              <div class="form-check">
                <%= b.check_box(class: 'form-check-input') %>
                <%= b.label(class: 'form-check-label') %>
              </div>
            <% end %>
          <% else %>
            <p class="text-danger">Nenhum funcionário disponível.</p>
          <% end %>
          <div class="modal-footer">
            <%= form.submit "Confirmar", class: "btn btn-primary", disabled: @funcionarios.none? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/agendamentos/_form.html.erb
<%= form_with(model: agendamento) do |form| %>
  <% if agendamento.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(agendamento.errors.count, "erro") %> <%= "encontrado".pluralize(agendamento.errors.count) %></h4>

      <ul>
        <% agendamento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :veiculo_id, "Veículo", class: "form-label" %>
    <%= form.collection_select :veiculo_id, @veiculos, :id, :modelo, { prompt: "Selecione um veículo" }, { class: 'form-select', id: 'veiculo_select' } %>
  </div>

  <div class="mb-3">
    <%= form.label :servico_id, class: "form-label" %>
    <%= form.collection_select :servico_id, Servico.all, :id, :nome, { prompt: "Selecione um serviço" }, { class: 'form-select' } %>
  </div>

  <div class="mb-3">
    <%= form.label :data, class: "form-label" %>
    <%= form.date_field :data, class: "form-control" %>
  </div>

  <div class="text-center">
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/agendamentos/edit.html.erb
<% content_for :title, "Editar agendamento" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="d-flex align-items-center mb-4">
        <%= link_to "Voltar", agendamentos_path, class: "btn btn-secondary me-3" %>
        <div class="flex-grow-1 text-center">
          <h1>Editar agendamento</h1>
        </div>
        <div class="fixed-size-div"></div>
      </div>

      <%= render "form", agendamento: @agendamento %>
    </div>
  </div>
</div>

app/views/agendamentos/index.html.erb
<% if notice %>
  <div class="alert alert-success"> <%= notice %> </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger"> <%= alert %> </div>
<% end %>

<% content_for :title, "Agendamentos" %>

<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>Agendamentos</h1>
  <%= link_to "Novo agendamento", new_agendamento_path, class: "btn btn-primary" %>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>ID</th>
    <th>Veículo</th>
    <th>Serviço</th>
    <th>Data</th>
    <th>Status</th>
    <th colspan="3">Ações</th>
  </tr>
  </thead>
  <tbody>
  <% @agendamentos.each do |agendamento| %>
    <tr>
      <td><%= agendamento.id %></td>
      <td><%= agendamento.veiculo.modelo %></td>
      <td><%= agendamento.servico.nome %></td>
      <td><%= agendamento.data.strftime("%d/%m/%Y") %></td>
      <td>
          <span class="status-badge <%= status_class(agendamento.status) %>">
            <%= agendamento.status.humanize %>
          </span>
      </td>
      <% if current_user.admin? %>
        <% if agendamento.status == "pendente" %>
          <td>
            <%= link_to "Aprovar", "#",
                        data: { bs_toggle: "modal", bs_target: "#approveStatusModal" },
                        class: "btn btn-primary btn-sm",
                        onclick: "document.getElementById('modal_agendamento_id').value = #{agendamento.id};
                                  document.getElementById('modal_status_field').value = 'confirmado';" %>
          </td>
          <td>
            <%= form_with url: update_status_agendamentos_path, method: :patch, local: true do |form| %>
              <%= hidden_field_tag :status, 'reprovado' %>
              <%= hidden_field_tag :agendamento_id, agendamento.id %>
              <%= submit_tag 'Reprovar', class: 'btn btn-danger btn-sm', data: { turbo_confirm: 'Tem certeza que deseja reprovar este agendamento?' } %>
            <% end %>
          </td>
        <% end %>

      <% end %>

      <td><%= link_to "Exibir", agendamento, class: "btn btn-info btn-sm" %></td>
      <% unless current_user.admin? %>
        <td><%= link_to "Editar", edit_agendamento_path(agendamento), class: "btn btn-warning btn-sm" %></td>
        <td><%= link_to "Excluir", agendamento, method: :delete, data: { confirm: "Tem certeza que deseja excluir este agendamento?" }, class: "btn btn-danger btn-sm" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'agendamentos/approve_status_modal' %>

app/views/agendamentos/new.html.erb
<% content_for :title, "Novo agendamento" %>

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="d-flex align-items-center mb-4">
        <%= link_to "Voltar", agendamentos_path, class: "btn btn-secondary me-3" %>
        <div class="flex-grow-1 text-center">
          <h1>Novo agendamento</h1>
        </div>
        <div class="fixed-size-div"></div>
      </div>

      <%= render "form", agendamento: @agendamento %>
    </div>
  </div>
</div>

app/views/agendamentos/show.html.erb
<div class="container mt-4">
  <% if notice %>
    <div class="alert alert-success"> <%= notice %> </div>
  <% end %>

  <div class="mb-4">
    <%= render @agendamento %>
  </div>

  <div class="d-flex justify-content-between">
    <div>
      <%= link_to "Voltar para agendamentos", agendamentos_path, class: "btn btn-secondary" %>
    </div>
    <div class="d-flex">
      <%= link_to "Editar agendamento", edit_agendamento_path(@agendamento), class: "btn btn-warning me-2" %>
      <%= confirm_delete_button "Excluir agendamento", @agendamento, { class: "btn btn-danger" } %>
    </div>
  </div>
</div>