config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    root "home#index"
    resources :atendimentos
    resources :estoques
    resources :servicos
    resources :funcionarios
    resources :clientes
    resources :veiculos
    resources :pecas
    resources :venda_servicos
    resources :agendamentos do
      patch :update_status, on: :collection
    end
    resources :clientes do
      get :veiculos, on: :member
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/agendamento.rb
class Agendamento < ApplicationRecord
  belongs_to :veiculo
  belongs_to :servico

  enum :status, { pendente: 0, confirmado: 1, reprovado: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :veiculo
  has_and_belongs_to_many :funcionarios

  enum :status, { agendado: 0, andamento: 1, concluido: 2, cancelado: 3 }

  validates :data_inicio, :data_termino, :status, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_one :user, dependent: :destroy
  has_many :veiculos, dependent: :destroy

  validates :nome, presence: true, length: { in: 3..80 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :telefone, presence: true, length: { minimum: 11, maximum: 11 }
  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11, maximum: 11 }
  validates :endereco, presence: true, length: { in: 3..80 }
end

app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :peca

  validates :codigo, presence: true, uniqueness: true
  validates :quantidade, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  has_and_belongs_to_many :atendimentos

  validates :matricula, presence: true, uniqueness: true
  validates :nome, presence: true, length: { in: 3..80 }
  validates :cpf, presence: true, uniqueness: true, length: { minimum: 11, maximum: 11 }
  validates :cargo, presence: true, length: { minimum: 5 }
  validates :email, presence: true
  validates :salario, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :data_admissao, presence: true
end

app/models/peca.rb
class Peca < ApplicationRecord
  has_many :estoques, dependent: :destroy

  validates :codigo, presence: true, uniqueness: true
  validates :nome, presence: true, length: { in: 2..20 }
  validates :preco, :tipo, :fabricante, :data_validade, presence: true
end

app/models/servico.rb
class Servico < ApplicationRecord
  has_many :atendimentos

  validates :codigo, presence: true, uniqueness: true
  validates :nome, presence: true
  validates :descricao, presence: true, length: { maximum: 100 }
  validates :preco, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :cliente, optional: true

  enum :role, [ :cliente, :admin ]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente
  has_many :atendimentos

  validates :placa, presence: true, uniqueness: true, length: { minimum: 7, maximum: 7 }
  validates :modelo, presence: true, length: { minimum: 3, maximum: 30 }
  validates :ano, presence: true, numericality: { only_integer: true }
  validates :cor, presence: true, length: { minimum: 3, maximum: 15 }
  validates :quilometragem, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :chassi, presence: true, length: { minimum: 17, maximum: 17 }, uniqueness: { case_sensitive: false }

end

app/models/venda_servico.rb
class VendaServico < ApplicationRecord
  belongs_to :servico
  belongs_to :cliente
  belongs_to :veiculo
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      render :index_admin
    else
      render :index_cliente
    end
  end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status_class(status)
    case status
    when "pendente", "agendado"
      "badge-pending"
    when "confirmado"
      "badge-confirmed"
    when "andamento"
      "badge-in-progress"
    when "concluido"
      "badge-completed"
    else
      "badge-secondary"
    end
  end

  def confirm_delete_button(name, path, options = {})
    default_options = { method: :delete, data: { turbo_confirm: "Tem certeza que deseja excluir?" } }
    options = default_options.merge(options)
    button_to name, path, options
  end
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pecas_helper.rb
module PecasHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/home/index_admin.html.erb
<% if notice %>
  <div class="alert alert-success"> <%= notice %></div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col text-center">
      <h1 class="display-4">Gerenciamento de Oficina de Automóveis</h1>
    </div>
  </div>

  <div class="row justify-content-center mt-4">

    <div class="col-md-3 mb-4">
      <a href="<%= atendimentos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-tools fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Atendimentos</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= agendamentos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-calendar-alt fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Agendamentos</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= clientes_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-user fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Clientes</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= veiculos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-car fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Veículos</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= estoques_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-boxes fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Estoques</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= pecas_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-cogs fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Peças</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= funcionarios_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-users fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Funcionários</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= servicos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-wrench fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Serviços</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= venda_servicos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-dollar-sign fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Vendas</h5>
        </div>
      </a>
    </div>
  </div>
</div>

<style>

    .card-hover .card {
        transition: background-color 0.3s, color 0.3s;
    }

    .card-hover:hover .card {
        background-color: #007bff;
        color: #ffffff;
    }

    .card-hover:hover .card .card-title {
        color: #ffffff;
    }
</style>

app/views/home/index_cliente.html.erb
<% if notice %>
  <div class="alert alert-success"> <%= notice %> </div>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col text-center">
      <h1 class="display-4">Gerenciamento de Oficina de Automóveis</h1>
    </div>
  </div>

  <div class="row justify-content-center mt-4">

    <div class="col-md-3 mb-4">
      <a href="<%= atendimentos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-tools fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Histórico de atendimentos</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= agendamentos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-calendar-alt fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Agendamentos</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= veiculos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-car fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Veículos</h5>
        </div>
      </a>
    </div>


    <div class="col-md-3 mb-4">
      <a href="<%= venda_servicos_path %>" class="text-decoration-none card-hover">
        <div class="card p-4 text-center shadow-sm">
          <i class="fas fa-dollar-sign fa-3x text-success mb-3"></i>
          <h5 class="card-title text-dark">Histórico serviços</h5>
        </div>
      </a>
    </div>
  </div>
</div>

<style>

    .card-hover .card {
        transition: background-color 0.3s, color 0.3s;
    }

    .card-hover:hover .card {
        background-color: #007bff;
        color: #ffffff;
    }

    .card-hover:hover .card .card-title {
        color: #ffffff;
    }
</style>